# Generated by Django 2.2.3 on 2019-08-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='spacex',
            new_name='Data',
        ),
    ]
