# Generated by Django 2.2.3 on 2019-08-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0002_auto_20190822_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='mission_patch',
            field=models.URLField(null=True),
        ),
    ]
