# Generated by Django 2.2.3 on 2019-08-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0003_auto_20190822_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='id',
        ),
        migrations.AlterField(
            model_name='data',
            name='flight_number',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='flight_number'),
        ),
    ]
