# Generated by Django 2.2.3 on 2019-08-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0005_auto_20190822_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='launch_date',
            field=models.DateTimeField(),
        ),
    ]
