# Generated by Django 2.2.3 on 2019-08-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='spaceClass',
            fields=[
                ('flight_number', models.IntegerField(primary_key=True, serialize=False)),
                ('rocket_name', models.CharField(max_length=150)),
                ('mission_patch', models.CharField(max_length=150, null=True)),
                ('launch_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
